/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiscyberarkv1alpha1 "github.com/clbiggs/cyberark-to-k8s/pkg/k8s/apis/cyberark/v1alpha1"
	versioned "github.com/clbiggs/cyberark-to-k8s/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/clbiggs/cyberark-to-k8s/pkg/k8s/client/informers/externalversions/internalinterfaces"
	cyberarkv1alpha1 "github.com/clbiggs/cyberark-to-k8s/pkg/k8s/client/listers/cyberark/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CyberArkInformer provides access to a shared informer and lister for
// CyberArks.
type CyberArkInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cyberarkv1alpha1.CyberArkLister
}

type cyberArkInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCyberArkInformer constructs a new informer for CyberArk type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCyberArkInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCyberArkInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCyberArkInformer constructs a new informer for CyberArk type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCyberArkInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BiggsV1alpha1().CyberArks(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BiggsV1alpha1().CyberArks(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BiggsV1alpha1().CyberArks(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BiggsV1alpha1().CyberArks(namespace).Watch(ctx, options)
			},
		},
		&apiscyberarkv1alpha1.CyberArk{},
		resyncPeriod,
		indexers,
	)
}

func (f *cyberArkInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCyberArkInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cyberArkInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiscyberarkv1alpha1.CyberArk{}, f.defaultInformer)
}

func (f *cyberArkInformer) Lister() cyberarkv1alpha1.CyberArkLister {
	return cyberarkv1alpha1.NewCyberArkLister(f.Informer().GetIndexer())
}
