//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyberArk) DeepCopyInto(out *CyberArk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyberArk.
func (in *CyberArk) DeepCopy() *CyberArk {
	if in == nil {
		return nil
	}
	out := new(CyberArk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CyberArk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyberArkAccount) DeepCopyInto(out *CyberArkAccount) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyberArkAccount.
func (in *CyberArkAccount) DeepCopy() *CyberArkAccount {
	if in == nil {
		return nil
	}
	out := new(CyberArkAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyberArkList) DeepCopyInto(out *CyberArkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CyberArk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyberArkList.
func (in *CyberArkList) DeepCopy() *CyberArkList {
	if in == nil {
		return nil
	}
	out := new(CyberArkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CyberArkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyberArkSpec) DeepCopyInto(out *CyberArkSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	out.Account = in.Account
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyberArkSpec.
func (in *CyberArkSpec) DeepCopy() *CyberArkSpec {
	if in == nil {
		return nil
	}
	out := new(CyberArkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyberArkStatus) DeepCopyInto(out *CyberArkStatus) {
	*out = *in
	in.LastSync.DeepCopyInto(&out.LastSync)
	in.AccountUpdate.DeepCopyInto(&out.AccountUpdate)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyberArkStatus.
func (in *CyberArkStatus) DeepCopy() *CyberArkStatus {
	if in == nil {
		return nil
	}
	out := new(CyberArkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyberArkTarget) DeepCopyInto(out *CyberArkTarget) {
	*out = *in
	in.Secret.DeepCopyInto(&out.Secret)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyberArkTarget.
func (in *CyberArkTarget) DeepCopy() *CyberArkTarget {
	if in == nil {
		return nil
	}
	out := new(CyberArkTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyberArkTargetSecret) DeepCopyInto(out *CyberArkTargetSecret) {
	*out = *in
	if in.UsernameKeys != nil {
		in, out := &in.UsernameKeys, &out.UsernameKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PasswordKeys != nil {
		in, out := &in.PasswordKeys, &out.PasswordKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalSecrets != nil {
		in, out := &in.AdditionalSecrets, &out.AdditionalSecrets
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyberArkTargetSecret.
func (in *CyberArkTargetSecret) DeepCopy() *CyberArkTargetSecret {
	if in == nil {
		return nil
	}
	out := new(CyberArkTargetSecret)
	in.DeepCopyInto(out)
	return out
}
