/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	cyberarkv1alpha1 "github.com/clbiggs/cyberark-to-k8s/pkg/k8s/apis/cyberark/v1alpha1"
	scheme "github.com/clbiggs/cyberark-to-k8s/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CyberArksGetter has a method to return a CyberArkInterface.
// A group's client should implement this interface.
type CyberArksGetter interface {
	CyberArks(namespace string) CyberArkInterface
}

// CyberArkInterface has methods to work with CyberArk resources.
type CyberArkInterface interface {
	Create(ctx context.Context, cyberArk *cyberarkv1alpha1.CyberArk, opts v1.CreateOptions) (*cyberarkv1alpha1.CyberArk, error)
	Update(ctx context.Context, cyberArk *cyberarkv1alpha1.CyberArk, opts v1.UpdateOptions) (*cyberarkv1alpha1.CyberArk, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cyberArk *cyberarkv1alpha1.CyberArk, opts v1.UpdateOptions) (*cyberarkv1alpha1.CyberArk, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*cyberarkv1alpha1.CyberArk, error)
	List(ctx context.Context, opts v1.ListOptions) (*cyberarkv1alpha1.CyberArkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *cyberarkv1alpha1.CyberArk, err error)
	CyberArkExpansion
}

// cyberArks implements CyberArkInterface
type cyberArks struct {
	*gentype.ClientWithList[*cyberarkv1alpha1.CyberArk, *cyberarkv1alpha1.CyberArkList]
}

// newCyberArks returns a CyberArks
func newCyberArks(c *BiggsV1alpha1Client, namespace string) *cyberArks {
	return &cyberArks{
		gentype.NewClientWithList[*cyberarkv1alpha1.CyberArk, *cyberarkv1alpha1.CyberArkList](
			"cyberarks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *cyberarkv1alpha1.CyberArk { return &cyberarkv1alpha1.CyberArk{} },
			func() *cyberarkv1alpha1.CyberArkList { return &cyberarkv1alpha1.CyberArkList{} },
		),
	}
}
